name: Composer (php-actions)

on: [push]


jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:latest
        ports:
          - 3306
        env:
          MYSQL_DATABASE: wordpress

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          composer_version: 2
          php_version: 7.4
          args: --dev

      - name: Run tests
        uses: php-actions/composer@v6
        with:
          composer_version: 2
          php_version: 7.4
          command: run phpunit