name: Test
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Lint and Test
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: composer install && npm install
    - name: Run lint
      run: composer lint
    - name: Run unit tests
      run: composer test
